name: CI Docker Hub

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: cine0831/action-test:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Container Build Success\n Image digest : ${{ steps.docker_build.outputs.digest }}'
          SLACK_TITLE: Container Build Success
          SLACK_USERNAME: GA-CI-Container
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

